name 'firewall'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures firewall'
long_description 'Installs/Configures firewall'
version '0.1.0'
